name: DartSimpleChat_Server
version: 0.0.1
author: Aleksandr (jjasper22@gmail.com)
description: Simple Dart based chat server
homepage: https://github.com/jasper22/DartSimpleChat
environment:
  sdk: '>=0.4.3'
dependencies:
  unittest: any
  log4dart:
    git: git://github.com/ltackmann/log4dart.git
  mongo_dart:
    git: git://github.com/vadimtsushko/mongo_dart.git

#dependencies:
#  js: any
#  unittest: any